---

- hosts: 127.0.0.1
  connection: local
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python3.6/site-packages"


  tasks:
  - name: Start containers
    docker_container:
      name: "{{ item.name }}"
      network_mode: host
      recreate: yes
      image: zoid/sbtest:flask
      cleanup: yes
      env:
        PORT: "{{ item.port }}"
    with_items:
       - { name: 'flask0', port: '5000' }
       - { name: 'flask1', port: '5001' }
       - { name: 'flask2', port: '5002' }
  
  - name: Template a file 
    template:
      src: nginx.conf
      dest: /nginx.conf
    with_items:
      - 5000
      - 5001
      - 5002

  - name: Template nginx.conf
    template:
      src: nginx.conf
      dest: nginx/nginx.conf
    with_items:
      - 5000
      - 5001
      - 5002
  
  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: /home/jenkins/ansible/nginx
      name: nginx
      tag: latest      
      source: build
